name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2.6.0
        with:
          arguments: build

      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: trelloServer
          path: build/libs/LinkCargoServer-0.0.1-SNAPSHOT.jar

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v2
        with:
          name: trelloServer
          path: build/libs/

      - name: Deploy to EC2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "${{ secrets.AWS_EC2_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem
          scp -i private_key.pem -o StrictHostKeyChecking=no build/libs/LinkCargoServer-0.0.1-SNAPSHOT.jar ${{ secrets.AWS_HOST_USER }}@${{ secrets.AWS_HOST_IP }}:/home/${{ secrets.AWS_HOST_USER }}/LinkCargoServer.jar
          ssh -i private_key.pem -o StrictHostKeyChecking=no ${{ secrets.AWS_HOST_USER }}@${{ secrets.AWS_HOST_IP }} "pgrep java | xargs kill -9; nohup java -jar /home/${{ secrets.AWS_HOST_USER }}/LinkCargoServer.jar > app.log 2>&1 &"
          rm -f private_key.pem
